### ISSUE TITLE
New Brazilian Prefix missing

### ISSUE THREAD

**Issue by ctriebstein** [ladutsko/isbn-core#2]
Brazil has two prefixes assigned: 978-85 and (new) 978-65. The latter doesn't occur in the `isbnRangeMessage.getRegistrationGroups()` return value.

**Comment by ladutsko** [comment]
@ctriebstein could you provide a couple of isbns to test? what version number of lib do you use?

**Comment by ctriebstein** [comment]
Some valid prefixes would be 
978-65-80309
978-65-80435
978-65-80034

We are currently using version 1.0.10

**Comment by ladutsko** [comment]
13:54:29.907 [main] DEBUG com.github.ladutsko.isbn.ISBNFormat - Put 4 range(s) for prefix 97865
13:54:29.908 [main] DEBUG com.github.ladutsko.isbn.ISBNFormat - Put 25 range(s) for prefix 97885

@ctriebstein  As I can see in test output both 978-65 and 978-85 prefixes are available. Please check your env or provide a snippet to reproduce.

**Comment by ctriebstein** [comment]
You're right - apparently we're using an old version of the RangeMessage.xml in our RangeMessageLoader. Issue can be closed
