### ISSUE TITLE
Switch to jakarta namespace

### ISSUE THREAD

**Issue by bmaehr** [ladutsko/isbn-core#6]
What is the plan about switching to jkarta namespace?

For example in `com.github.ladutsko.isbn.util.RangeMessageLoader` change `javax.xml.bind.JAXBContext` to `jakarta.xml.bind.JAXBContext`?

**Comment by bmaehr** [comment]
@ladutsko

**Comment by ladutsko** [comment]
Hi @bmaehr 
Please provide more details about the problem. What is you case?
Pay attention on library requirements - java 1.5+
jakarta package will break compatibility

**Comment by bmaehr** [comment]
Exactly. But the whole JEE world is switching to the new jakarta namespaces (Hibernate 6, Spring Boot 3, Spring 6, ...)

**Comment by ladutsko** [comment]
I will keep that in mind in future.
Thanks!

**Comment by bmaehr** [comment]
[java.zip](https://github.com/user-attachments/files/17165659/java.zip)
The changed sources
